name: doubletapp_habits
description: Flutter test project for doubletapp.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  intl: ^0.18.1
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.2

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        weight: 700
      - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
        weight: 800
